databaseChangeLog:
  - changeSet:
      id: 006-settings
      author: lms
      changes:
        - sqlFile:
            path: db/changelog/sql/tenant/006-settings.sql
            relativeToChangelogFile: false
            splitStatements: false
            stripComments: false
